# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  jellyfin-desktop-cef = {
    pname = "jellyfin-desktop-cef";
    version = "148.0.10+g7ee53f5+chromium-148.0.7778.218";
    src = fetchurl {
      url = "https://cef-builds.spotifycdn.com/cef_binary_148.0.10+g7ee53f5+chromium-148.0.7778.218_linux64_minimal.tar.bz2";
      sha256 = "sha256-tKcIC8OtMgjppwBQJsXwaXaN7lEr8ivJKRt7Nm6j+Mw=";
    };
  };
  jellyfin-desktop-libmpv = {
    pname = "jellyfin-desktop-libmpv";
    version = "3ccd26745a4d746367fd04e288a3eab004b0bd47";
    src = fetchgit {
      url = "https://github.com/andrewrabert/mpv.git";
      rev = "3ccd26745a4d746367fd04e288a3eab004b0bd47";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-GcFGk+2MwrF+0BDIN7LsZajkkaaCdAT1JE5wE/mqSwo=";
    };
    date = "2026-05-28";
  };
}
