# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  jellyfin-desktop-cef = {
    pname = "jellyfin-desktop-cef";
    version = "148.0.10+g7ee53f5+chromium-148.0.7778.218";
    src = fetchurl {
      url = "https://cef-builds.spotifycdn.com/cef_binary_148.0.10+g7ee53f5+chromium-148.0.7778.218_linux64_minimal.tar.bz2";
      sha256 = "sha256-tKcIC8OtMgjppwBQJsXwaXaN7lEr8ivJKRt7Nm6j+Mw=";
    };
  };
  jellyfin-desktop-libmpv = {
    pname = "jellyfin-desktop-libmpv";
    version = "a4399f48b4c872e5b8a0eb83ba3ff9b1f7a7add6";
    src = fetchgit {
      url = "https://github.com/andrewrabert/mpv.git";
      rev = "a4399f48b4c872e5b8a0eb83ba3ff9b1f7a7add6";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-26dK2aL5v+Lo7dnlm1SeIH3zYr5UP0p5eCxmTxGemyU=";
    };
    date = "2026-06-08";
  };
}
