# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  jellyfin-desktop-cef = {
    pname = "jellyfin-desktop-cef";
    version = "149.0.2+ged5b3fd+chromium-149.0.7827.53";
    src = fetchurl {
      url = "https://cef-builds.spotifycdn.com/cef_binary_149.0.2+ged5b3fd+chromium-149.0.7827.53_linux64_minimal.tar.bz2";
      sha256 = "sha256-nl3d8/rgcQMB41uUgOfB7EAEeY+IB8oAP+4fzhoFczg=";
    };
  };
  jellyfin-desktop-libmpv = {
    pname = "jellyfin-desktop-libmpv";
    version = "a4399f48b4c872e5b8a0eb83ba3ff9b1f7a7add6";
    src = fetchgit {
      url = "https://github.com/andrewrabert/mpv.git";
      rev = "a4399f48b4c872e5b8a0eb83ba3ff9b1f7a7add6";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-26dK2aL5v+Lo7dnlm1SeIH3zYr5UP0p5eCxmTxGemyU=";
    };
    date = "2026-06-08";
  };
}
