{
  description = "A convenient gaming flake for NixOS";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
    millennium = {
      url = "github:SteamClientHomebrew/Millennium?dir=packages/nix";
      inputs.nixpkgs.follows = "nixpkgs";
    };
  };

  nixConfig = {
    extra-substituters = [ "https://nix-cache.tokidoki.dev/tokidoki" ];
    extra-trusted-public-keys = [
      "tokidoki:MD4VWt3kK8Fmz3jkiGoNRJIW31/QAm7l1Dcgz2Xa4hk="
    ];
  };

  outputs =
    {
      self,
      nixpkgs,
      millennium,
    }:
    let
      system = "x86_64-linux";
      pkgs = import nixpkgs {
        inherit system;
        config.allowUnfree = true;
      };

      # sources as generated by nvfetcher -o _sources
      nvSources = pkgs.callPackage ./_sources/generated.nix { };

      # Mesa-git
      makeMesaPkgs =
        pkgs':
        import ./pkgs/mesa-git {
          pkgs = pkgs';
          mesa-src = nvSources.mesa.src // {
            rev = nvSources.mesa.version;
          };
          libdrm-src = nvSources.libdrm.src // {
            rev = nvSources.libdrm.version;
          };
          wayland-src = nvSources.wayland.src // {
            rev = nvSources.wayland.version;
          };
          wayland-protocols-src = nvSources.wayland-protocols.src // {
            rev = nvSources.wayland-protocols.version;
          };
        };
      mesaPkgs = makeMesaPkgs pkgs;

      mkProton =
        sourceKey: variantName:
        pkgs.callPackage ./pkgs/proton-cachyos {
          source = nvSources.${sourceKey};
          baseSource = nvSources.proton-cachyos;
          variant = variantName;
        };

      mkVintageStory =
        sourceKey:
        pkgs.callPackage ./pkgs/vintagestory {
          source = nvSources.${sourceKey};
        };

      proton = mkProton "proton-cachyos" "base";
      protonv2 = mkProton "proton-cachyos-x86_64-v2" "x86_64-v2";
      protonv3 = mkProton "proton-cachyos-x86_64-v3" "x86_64-v3";
      protonv4 = mkProton "proton-cachyos-x86_64-v4" "x86_64-v4";

      # Discord (stable) and Vencord (nightly)
      discord = pkgs.callPackage ./pkgs/discord {
        discordSrc = nvSources.discord;
        vencordSrc = nvSources.vencord;
      };

      # Fluxer Desktop
      fluxer-desktop = pkgs.callPackage ./pkgs/fluxer-desktop {
        source = nvSources.fluxer-desktop;
      };

      # ModEngine 3
      modengine3 = pkgs.callPackage ./pkgs/modengine3 {
        source = nvSources.modengine3;
      };

      # OpenGoal Launcher
      opengoal-launcher = pkgs.callPackage ./pkgs/opengoal-launcher {
        source = nvSources.opengoal-launcher;
      };

    in
    {
      packages.${pkgs.stdenv.hostPlatform.system} = {

        # Mesa-git
        mesa-git = mesaPkgs.mesa-git;
        mesa32-git = mesaPkgs.mesa32-git;
        libdrm-git = mesaPkgs.libdrm-git;
        libdrm32-git = mesaPkgs.libdrm32-git;
        wayland-protocols-git = mesaPkgs.wayland-protocols-git;

        # Proton CachyOS
        proton-cachyos = proton;
        proton-cachyos-x86_64-v2 = protonv2;
        proton-cachyos-x86_64-v3 = protonv3;
        proton-cachyos-x86_64-v4 = protonv4;
        # Deprecated aliases (w/ underscores) for backwards compatibility
        proton-cachyos-x86_64_v2 = protonv2;
        proton-cachyos-x86_64_v3 = protonv3;
        proton-cachyos-x86_64_v4 = protonv4;

        # Vintage Story
        vintagestory = mkVintageStory "vintagestory";

        # PokeMMO
        pokemmo = pkgs.callPackage ./pkgs/pokemmo {
          inherit (nvSources.pokemmo) src;
        };

        # Pseudoregalia Randomizer
        pseudoregalia-rando = pkgs.callPackage ./pkgs/pseudoregalia-rando {
          inherit (nvSources.pseudoregalia-rando) src version;
          oodleSrc = nvSources.oodle-lib.src;
        };

        # Eden Emulator
        eden-emulator = pkgs.callPackage ./pkgs/eden-emulator {
          inherit (nvSources.eden-emulator) version src;
        };
        eden = self.packages.${pkgs.stdenv.hostPlatform.system}.eden-emulator;

        # Hytale Launcher
        hytale-launcher = pkgs.callPackage ./pkgs/hytale-launcher {
          source = nvSources.hytale-launcher;
        };
        hytale = self.packages.${pkgs.stdenv.hostPlatform.system}.hytale-launcher;

        # Millennium for theming Steam
        millennium-steam = millennium.packages.${pkgs.stdenv.hostPlatform.system}.default;

        # Discord (stable) and Vencord (nightly)
        discord = discord.discord;
        vencord = discord.vencord;

        # Fluxer Desktop
        fluxer-desktop = fluxer-desktop;

        # ModEngine 3
        modengine3 = modengine3;

        # OpenGoal Launcher
        opengoal-launcher = opengoal-launcher;

        # Harkinian (Ship of Harkinian / 2 Ship 2 Harkinian)
        # Building these from Nixpkgs and pushing to Attic cache
        shipwright = pkgs.shipwright;
        _2ship2harkinian = pkgs._2ship2harkinian;
      };

      overlays = {
        default = final: prev: {
          mesa-git = self.packages.${final.stdenv.hostPlatform.system}.mesa-git;
          mesa32-git = self.packages.${final.stdenv.hostPlatform.system}.mesa32-git;
          libdrm-git = self.packages.${final.stdenv.hostPlatform.system}.libdrm-git;
          libdrm32-git = self.packages.${final.stdenv.hostPlatform.system}.libdrm32-git;
          wayland-protocols-git = self.packages.${final.stdenv.hostPlatform.system}.wayland-protocols-git;

          proton-cachyos = self.packages.${final.stdenv.hostPlatform.system}.proton-cachyos;
          proton-cachyos-x86_64-v2 =
            self.packages.${final.stdenv.hostPlatform.system}.proton-cachyos-x86_64-v2;
          proton-cachyos-x86_64-v3 =
            self.packages.${final.stdenv.hostPlatform.system}.proton-cachyos-x86_64-v3;
          proton-cachyos-x86_64-v4 =
            self.packages.${final.stdenv.hostPlatform.system}.proton-cachyos-x86_64-v4;
          # Deprecated aliases w/ underscores
          proton-cachyos-x86_64_v2 =
            self.packages.${final.stdenv.hostPlatform.system}.proton-cachyos-x86_64-v2;
          proton-cachyos-x86_64_v3 =
            self.packages.${final.stdenv.hostPlatform.system}.proton-cachyos-x86_64-v3;
          proton-cachyos-x86_64_v4 =
            self.packages.${final.stdenv.hostPlatform.system}.proton-cachyos-x86_64-v4;

          vintagestory = self.packages.${final.stdenv.hostPlatform.system}.vintagestory;

          pokemmo = self.packages.${final.stdenv.hostPlatform.system}.pokemmo;

          pseudoregalia-rando = self.packages.${final.stdenv.hostPlatform.system}.pseudoregalia-rando;

          eden-emulator = self.packages.${final.stdenv.hostPlatform.system}.eden-emulator;
          eden = self.packages.${final.stdenv.hostPlatform.system}.eden-emulator;

          hytale-launcher = self.packages.${final.stdenv.hostPlatform.system}.hytale-launcher;
          hytale = self.packages.${final.stdenv.hostPlatform.system}.hytale-launcher;

          millennium-steam = self.packages.${final.stdenv.hostPlatform.system}.millennium-steam;

          discord = self.packages.${final.stdenv.hostPlatform.system}.discord;
          vencord = self.packages.${final.stdenv.hostPlatform.system}.vencord;

          fluxer-desktop = self.packages.${final.stdenv.hostPlatform.system}.fluxer-desktop;

          modengine3 = self.packages.${final.stdenv.hostPlatform.system}.modengine3;

          opengoal-launcher = self.packages.${final.stdenv.hostPlatform.system}.opengoal-launcher;

          shipwright = self.packages.${final.stdenv.hostPlatform.system}.shipwright;
          _2ship2harkinian = self.packages.${final.stdenv.hostPlatform.system}._2ship2harkinian;
        };

        mesa-git = final: prev: {
          mesa-git = self.packages.${final.stdenv.hostPlatform.system}.mesa-git;
          mesa32-git = self.packages.${final.stdenv.hostPlatform.system}.mesa32-git;
          libdrm-git = self.packages.${final.stdenv.hostPlatform.system}.libdrm-git;
          libdrm32-git = self.packages.${final.stdenv.hostPlatform.system}.libdrm32-git;
          wayland-protocols-git = self.packages.${final.stdenv.hostPlatform.system}.wayland-protocols-git;
        };

        proton-cachyos = final: prev: {
          proton-cachyos = self.packages.${final.stdenv.hostPlatform.system}.proton-cachyos;
          proton-cachyos-x86_64-v2 =
            self.packages.${final.stdenv.hostPlatform.system}.proton-cachyos-x86_64-v2;
          proton-cachyos-x86_64-v3 =
            self.packages.${final.stdenv.hostPlatform.system}.proton-cachyos-x86_64-v3;
          proton-cachyos-x86_64-v4 =
            self.packages.${final.stdenv.hostPlatform.system}.proton-cachyos-x86_64-v4;

          # Deprecated aliases w/ underscores
          proton-cachyos-x86_64_v2 =
            self.packages.${final.stdenv.hostPlatform.system}.proton-cachyos-x86_64-v2;
          proton-cachyos-x86_64_v3 =
            self.packages.${final.stdenv.hostPlatform.system}.proton-cachyos-x86_64-v3;
          proton-cachyos-x86_64_v4 =
            self.packages.${final.stdenv.hostPlatform.system}.proton-cachyos-x86_64-v4;
        };

        vintagestory = final: prev: {
          vintagestory = self.packages.${final.stdenv.hostPlatform.system}.vintagestory;
        };

        pokemmo = final: prev: {
          pokemmo = self.packages.${final.stdenv.hostPlatform.system}.pokemmo;
        };

        pseudoregalia-rando = final: prev: {
          pseudoregalia-rando = self.packages.${final.stdenv.hostPlatform.system}.pseudoregalia-rando;
        };

        eden-emulator = final: prev: {
          eden-emulator = self.packages.${final.stdenv.hostPlatform.system}.eden-emulator;
          eden = self.packages.${final.stdenv.hostPlatform.system}.eden-emulator;
        };

        hytale-launcher = final: prev: {
          hytale-launcher = self.packages.${final.stdenv.hostPlatform.system}.hytale-launcher;
          hytale = self.packages.${final.stdenv.hostPlatform.system}.hytale-launcher;
        };

        millennium-steam = final: prev: {
          millennium-steam = self.packages.${final.stdenv.hostPlatform.system}.millennium-steam;
        };

        discord = final: prev: {
          discord = self.packages.${final.stdenv.hostPlatform.system}.discord;
          vencord = self.packages.${final.stdenv.hostPlatform.system}.vencord;
        };

        fluxer = final: prev: {
          fluxer-desktop = self.packages.${final.stdenv.hostPlatform.system}.fluxer-desktop;
        };

        modengine3 = final: prev: {
          modengine3 = self.packages.${final.stdenv.hostPlatform.system}.modengine3;
        };

        opengoal = final: prev: {
          opengoal-launcher = self.packages.${final.stdenv.hostPlatform.system}.opengoal-launcher;
        };

        harkinian = final: prev: {
          shipwright = self.packages.${final.stdenv.hostPlatform.system}.shipwright;
          _2ship2harkinian = self.packages.${final.stdenv.hostPlatform.system}._2ship2harkinian;
        };
      };

      nixosModules = {
        mesa-git = import ./modules/mesa-git.nix;
        default = self.nixosModules.mesa-git;
      };
    };
}
