{
  description = "A convenient gaming flake for NixOS";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
    # millennium-steam is currently broken upstream and disabled here.
    # Re-enable this input (and the related references below) if/when
    # upstream is fixed.
    # millennium = {
    #   url = "github:SteamClientHomebrew/Millennium?dir=packages/nix";
    #   inputs.nixpkgs.follows = "nixpkgs";
    # };
  };

  nixConfig = {
    extra-substituters = [ "https://nix-cache.tokidoki.dev/tokidoki" ];
    extra-trusted-public-keys = [
      "tokidoki:MD4VWt3kK8Fmz3jkiGoNRJIW31/QAm7l1Dcgz2Xa4hk="
    ];
  };

  outputs =
    {
      self,
      nixpkgs,
      # millennium, # disabled: millennium-steam is broken upstream
    }:
    let
      system = "x86_64-linux";
      pkgs = import nixpkgs {
        inherit system;
        config.allowUnfree = true;
      };

      # sources as generated by nvfetcher -o _sources
      nvSources = pkgs.callPackage ./_sources/generated.nix { };

      # Mesa-git
      makeMesaPkgs =
        pkgs':
        import ./pkgs/mesa-git {
          pkgs = pkgs';
          mesa-src = nvSources.mesa.src // {
            rev = nvSources.mesa.version;
          };
          libdrm-src = nvSources.libdrm.src // {
            rev = nvSources.libdrm.version;
          };
          wayland-src = nvSources.wayland.src // {
            rev = nvSources.wayland.version;
          };
          wayland-protocols-src = nvSources.wayland-protocols.src // {
            rev = nvSources.wayland-protocols.version;
          };
        };
      mesaPkgs = makeMesaPkgs pkgs;

      mkProton =
        sourceKey: variantName:
        pkgs.callPackage ./pkgs/proton-cachyos {
          source = nvSources.${sourceKey};
          baseSource = nvSources.proton-cachyos;
          variant = variantName;
        };

      mkVintageStory =
        sourceKey:
        pkgs.callPackage ./pkgs/vintagestory {
          source = nvSources.${sourceKey};
        };

      proton = mkProton "proton-cachyos" "base";
      protonv3 = mkProton "proton-cachyos-x86_64-v3" "x86_64-v3";

      # Discord (stable) and Vencord (nightly)
      discord = pkgs.callPackage ./pkgs/discord {
        vencordSrc = nvSources.vencord;
      };

      # Fluxer Desktop (upstream prebuilt tarballs, patchelf'd)
      fluxer-desktop = pkgs.callPackage ./pkgs/fluxer-desktop {
        source = nvSources.fluxer-desktop;
        channel = "stable";
      };
      fluxer-desktop-canary = pkgs.callPackage ./pkgs/fluxer-desktop {
        source = nvSources.fluxer-desktop-canary;
        channel = "canary";
      };

      # ModEngine 3
      modengine3 = pkgs.callPackage ./pkgs/modengine3 {
        source = nvSources.modengine3;
      };

      # OpenGoal Launcher
      opengoal-launcher = pkgs.callPackage ./pkgs/opengoal-launcher {
        source = nvSources.opengoal-launcher;
      };

      # Harkinian (Ship of Harkinian / 2 Ship 2 Harkinian)
      harkinian = pkgs.callPackage ./pkgs/harkinian {
        shipwrightSrc = nvSources.shipwright;
        _2ship2harkinianSrc = nvSources._2ship2harkinian;
      };

      # Jellyfin Desktop v3 (CEF + mpv source build)
      jellyfin-desktop = pkgs.callPackage ./pkgs/jellyfin-desktop {
        source = nvSources.jellyfin-desktop;
      };

    in
    {
      packages.${pkgs.stdenv.hostPlatform.system} = {

        # Mesa-git
        mesa-git = mesaPkgs.mesa-git;
        mesa32-git = mesaPkgs.mesa32-git;
        libdrm-git = mesaPkgs.libdrm-git;
        libdrm32-git = mesaPkgs.libdrm32-git;
        wayland-protocols-git = mesaPkgs.wayland-protocols-git;

        # Proton CachyOS
        proton-cachyos = proton;
        proton-cachyos-x86_64-v3 = protonv3;
        # Deprecated aliases (w/ underscores) for backwards compatibility
        proton-cachyos-x86_64_v3 = protonv3;

        # Vintage Story
        vintagestory = mkVintageStory "vintagestory";

        # PokeMMO
        pokemmo = pkgs.callPackage ./pkgs/pokemmo {
          inherit (nvSources.pokemmo) src;
        };

        # Pseudoregalia Randomizer
        pseudoregalia-rando = pkgs.callPackage ./pkgs/pseudoregalia-rando {
          inherit (nvSources.pseudoregalia-rando) src version;
          oodleSrc = nvSources.oodle-lib.src;
        };

        # Hytale Launcher
        hytale-launcher = pkgs.callPackage ./pkgs/hytale-launcher {
          source = nvSources.hytale-launcher;
        };
        hytale = self.packages.${pkgs.stdenv.hostPlatform.system}.hytale-launcher;

        # Millennium for theming Steam
        # Disabled: broken upstream and unable to build. Re-enable if/when fixed.
        # millennium-steam = millennium.packages.${pkgs.stdenv.hostPlatform.system}.default;

        # Discord (stable) and Vencord (nightly)
        discord = discord.discord;
        vencord = discord.vencord;

        # Fluxer Desktop
        fluxer-desktop = fluxer-desktop;
        fluxer-desktop-canary = fluxer-desktop-canary;

        # ModEngine 3
        modengine3 = modengine3;

        # OpenGoal Launcher
        opengoal-launcher = opengoal-launcher;

        # Harkinian (Ship of Harkinian / 2 Ship 2 Harkinian)
        # Source tracked by nvfetcher to stay ahead of Nixpkgs hash updates
        shipwright = harkinian.shipwright;
        _2ship2harkinian = harkinian._2ship2harkinian;

        # Jellyfin Desktop v3
        jellyfin-desktop = jellyfin-desktop;
      };

      overlays = {
        # Inside FHS envs, swap stable libdrm for libdrm-git (mesa-git needs it)
        libdrmGitFhsenv = import ./overlays/libdrm-git-fhsenv.nix;

        default = final: prev: {
          mesa-git = self.packages.${final.stdenv.hostPlatform.system}.mesa-git;
          mesa32-git = self.packages.${final.stdenv.hostPlatform.system}.mesa32-git;
          libdrm-git = self.packages.${final.stdenv.hostPlatform.system}.libdrm-git;
          libdrm32-git = self.packages.${final.stdenv.hostPlatform.system}.libdrm32-git;
          wayland-protocols-git = self.packages.${final.stdenv.hostPlatform.system}.wayland-protocols-git;

          proton-cachyos = self.packages.${final.stdenv.hostPlatform.system}.proton-cachyos;
          proton-cachyos-x86_64-v3 =
            self.packages.${final.stdenv.hostPlatform.system}.proton-cachyos-x86_64-v3;
          # Deprecated aliases w/ underscores
          proton-cachyos-x86_64_v3 =
            self.packages.${final.stdenv.hostPlatform.system}.proton-cachyos-x86_64-v3;

          vintagestory = self.packages.${final.stdenv.hostPlatform.system}.vintagestory;

          pokemmo = self.packages.${final.stdenv.hostPlatform.system}.pokemmo;

          pseudoregalia-rando = self.packages.${final.stdenv.hostPlatform.system}.pseudoregalia-rando;

          hytale-launcher = self.packages.${final.stdenv.hostPlatform.system}.hytale-launcher;
          hytale = self.packages.${final.stdenv.hostPlatform.system}.hytale-launcher;

          # Disabled: millennium-steam is broken upstream. Re-enable if/when fixed.
          # millennium-steam = self.packages.${final.stdenv.hostPlatform.system}.millennium-steam;

          discord = self.packages.${final.stdenv.hostPlatform.system}.discord;
          vencord = self.packages.${final.stdenv.hostPlatform.system}.vencord;

          fluxer-desktop = self.packages.${final.stdenv.hostPlatform.system}.fluxer-desktop;
          fluxer-desktop-canary = self.packages.${final.stdenv.hostPlatform.system}.fluxer-desktop-canary;

          modengine3 = self.packages.${final.stdenv.hostPlatform.system}.modengine3;

          opengoal-launcher = self.packages.${final.stdenv.hostPlatform.system}.opengoal-launcher;

          shipwright = self.packages.${final.stdenv.hostPlatform.system}.shipwright;
          _2ship2harkinian = self.packages.${final.stdenv.hostPlatform.system}._2ship2harkinian;

          jellyfin-desktop = self.packages.${final.stdenv.hostPlatform.system}.jellyfin-desktop;
        };

        mesa-git = final: prev: {
          mesa-git = self.packages.${final.stdenv.hostPlatform.system}.mesa-git;
          mesa32-git = self.packages.${final.stdenv.hostPlatform.system}.mesa32-git;
          libdrm-git = self.packages.${final.stdenv.hostPlatform.system}.libdrm-git;
          libdrm32-git = self.packages.${final.stdenv.hostPlatform.system}.libdrm32-git;
          wayland-protocols-git = self.packages.${final.stdenv.hostPlatform.system}.wayland-protocols-git;
        };

        proton-cachyos = final: prev: {
          proton-cachyos = self.packages.${final.stdenv.hostPlatform.system}.proton-cachyos;
          proton-cachyos-x86_64-v3 =
            self.packages.${final.stdenv.hostPlatform.system}.proton-cachyos-x86_64-v3;

          # Deprecated aliases w/ underscores
          proton-cachyos-x86_64_v3 =
            self.packages.${final.stdenv.hostPlatform.system}.proton-cachyos-x86_64-v3;
        };

        vintagestory = final: prev: {
          vintagestory = self.packages.${final.stdenv.hostPlatform.system}.vintagestory;
        };

        pokemmo = final: prev: {
          pokemmo = self.packages.${final.stdenv.hostPlatform.system}.pokemmo;
        };

        pseudoregalia-rando = final: prev: {
          pseudoregalia-rando = self.packages.${final.stdenv.hostPlatform.system}.pseudoregalia-rando;
        };

        hytale-launcher = final: prev: {
          hytale-launcher = self.packages.${final.stdenv.hostPlatform.system}.hytale-launcher;
          hytale = self.packages.${final.stdenv.hostPlatform.system}.hytale-launcher;
        };

        # Disabled: millennium-steam is broken upstream. Re-enable if/when fixed.
        # millennium-steam = final: prev: {
        #   millennium-steam = self.packages.${final.stdenv.hostPlatform.system}.millennium-steam;
        # };

        discord = final: prev: {
          discord = self.packages.${final.stdenv.hostPlatform.system}.discord;
          vencord = self.packages.${final.stdenv.hostPlatform.system}.vencord;
        };

        fluxer = final: prev: {
          fluxer-desktop = self.packages.${final.stdenv.hostPlatform.system}.fluxer-desktop;
          fluxer-desktop-canary = self.packages.${final.stdenv.hostPlatform.system}.fluxer-desktop-canary;
        };

        modengine3 = final: prev: {
          modengine3 = self.packages.${final.stdenv.hostPlatform.system}.modengine3;
        };

        opengoal = final: prev: {
          opengoal-launcher = self.packages.${final.stdenv.hostPlatform.system}.opengoal-launcher;
        };

        harkinian = final: prev: {
          shipwright = self.packages.${final.stdenv.hostPlatform.system}.shipwright;
          _2ship2harkinian = self.packages.${final.stdenv.hostPlatform.system}._2ship2harkinian;
        };

        jellyfin-desktop = final: prev: {
          jellyfin-desktop = self.packages.${final.stdenv.hostPlatform.system}.jellyfin-desktop;
        };
      };

      nixosModules = {
        mesa-git = import ./modules/mesa-git.nix;
        default = self.nixosModules.mesa-git;
      };
    };
}
