{
  description = "A convenient gaming flake for NixOS";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
    # millennium-steam is currently broken upstream and disabled here.
    # Re-enable this input (and the related references below) if/when
    # upstream is fixed.
    # millennium = {
    #   url = "github:SteamClientHomebrew/Millennium?dir=packages/nix";
    #   inputs.nixpkgs.follows = "nixpkgs";
    # };
  };

  nixConfig = {
    extra-substituters = [ "https://nix-cache.tokidoki.dev/tokidoki" ];
    extra-trusted-public-keys = [
      "tokidoki:MD4VWt3kK8Fmz3jkiGoNRJIW31/QAm7l1Dcgz2Xa4hk="
    ];
  };

  outputs =
    {
      self,
      nixpkgs,
      # millennium, # disabled: millennium-steam is broken upstream
    }:
    let
      inherit (nixpkgs) lib;

      linuxSystems = [ "x86_64-linux" ];
      darwinSystems = [ "aarch64-darwin" ];
      allSystems = linuxSystems ++ darwinSystems;
      forAllSystems = lib.genAttrs allSystems;

      mkPkgs =
        system:
        import nixpkgs {
          inherit system;
          config.allowUnfree = true;
        };

      # Packages that build on every supported system.
      crossPackages =
        pkgs:
        let
          # sources as generated by nvfetcher -o _sources
          nvSources = pkgs.callPackage ./_sources/generated.nix { };

          # Discord (stable) and Vencord (nightly)
          discord = pkgs.callPackage ./pkgs/discord {
            vencordSrc = nvSources.vencord;
          };

        in
        {
          discord = discord.discord;
          vencord = discord.vencord;

          # Fluxer Desktop (Linux tarball or darwin .app zip, tracked per platform by nvfetcher).
          # Upstream dropped the stable channel 2026-09-02; the canary feed is the only client now.
          fluxer-desktop = pkgs.callPackage ./pkgs/fluxer-desktop {
            source = nvSources.${"fluxer-desktop" + lib.optionalString pkgs.stdenv.hostPlatform.isDarwin "-darwin"};
          };
        };

      # Packages that only build on Linux.
      linuxPackages =
        pkgs:
        let
          # sources as generated by nvfetcher -o _sources
          nvSources = pkgs.callPackage ./_sources/generated.nix { };

          # Mesa-git
          makeMesaPkgs =
            pkgs':
            import ./pkgs/mesa-git {
              pkgs = pkgs';
              mesa-src = nvSources.mesa.src // {
                rev = nvSources.mesa.version;
              };
              libdrm-src = nvSources.libdrm.src // {
                rev = nvSources.libdrm.version;
              };
              wayland-src = nvSources.wayland.src // {
                rev = nvSources.wayland.version;
              };
              wayland-protocols-src = nvSources.wayland-protocols.src // {
                rev = nvSources.wayland-protocols.version;
              };
            };
          mesaPkgs = makeMesaPkgs pkgs;

          mkProton =
            sourceKey: variantName:
            pkgs.callPackage ./pkgs/proton-cachyos {
              source = nvSources.${sourceKey};
              variant = variantName;
            };

          mkVintageStory =
            sourceKey:
            pkgs.callPackage ./pkgs/vintagestory {
              source = nvSources.${sourceKey};
            };

          proton = mkProton "proton-cachyos" "base";
          protonv3 = mkProton "proton-cachyos-x86_64-v3" "x86_64-v3";

          # ModEngine 3
          modengine3 = pkgs.callPackage ./pkgs/modengine3 {
            source = nvSources.modengine3;
          };

          # OpenGoal Launcher
          opengoal-launcher = pkgs.callPackage ./pkgs/opengoal-launcher {
            source = nvSources.opengoal-launcher;
          };

          # Jellium Desktop (CEF + mpv source build; formerly jellyfin-desktop v3)
          jellium-desktop = pkgs.callPackage ./pkgs/jellium-desktop {
            source = nvSources.jellium-desktop;
          };

          hytale-launcher = pkgs.callPackage ./pkgs/hytale-launcher {
            source = nvSources.hytale-launcher;
          };
        in
        {
          # Mesa-git
          mesa-git = mesaPkgs.mesa-git;
          mesa32-git = mesaPkgs.mesa32-git;
          libdrm-git = mesaPkgs.libdrm-git;
          libdrm32-git = mesaPkgs.libdrm32-git;
          wayland-protocols-git = mesaPkgs.wayland-protocols-git;

          # Proton CachyOS
          proton-cachyos = proton;
          proton-cachyos-x86_64-v3 = protonv3;
          # Deprecated aliases (w/ underscores) for backwards compatibility
          proton-cachyos-x86_64_v3 = protonv3;

          # Vintage Story
          vintagestory = mkVintageStory "vintagestory";

          # PokeMMO
          pokemmo = pkgs.callPackage ./pkgs/pokemmo {
            inherit (nvSources.pokemmo) src;
          };

          # Pseudoregalia Randomizer
          pseudoregalia-rando = pkgs.callPackage ./pkgs/pseudoregalia-rando {
            inherit (nvSources.pseudoregalia-rando) src version;
            oodleSrc = nvSources.oodle-lib.src;
          };

          # Hytale Launcher
          inherit hytale-launcher;
          hytale = hytale-launcher;

          # Millennium for theming Steam
          # Disabled: broken upstream and unable to build. Re-enable if/when fixed.
          # millennium-steam = millennium.packages.${pkgs.stdenv.hostPlatform.system}.default;

          # ModEngine 3
          inherit modengine3;

          # OpenGoal Launcher
          inherit opengoal-launcher;

          # Jellium Desktop
          inherit jellium-desktop;
        };

      packagesFor =
        system:
        let
          pkgs = mkPkgs system;
        in
        crossPackages pkgs // lib.optionalAttrs (builtins.elem system linuxSystems) (linuxPackages pkgs);

      # Overlay of the named packages, skipping any missing on this system; the system must come from `prev` (attr names from `final` recurse).
      mkOverlay =
        names: final: prev:
        lib.filterAttrs (n: _: builtins.elem n names) (
          self.packages.${prev.stdenv.hostPlatform.system} or { }
        );
    in
    {
      packages = forAllSystems packagesFor;

      overlays = {
        default = final: prev: self.packages.${prev.stdenv.hostPlatform.system} or { };

        mesa-git = mkOverlay [
          "mesa-git"
          "mesa32-git"
          "libdrm-git"
          "libdrm32-git"
          "wayland-protocols-git"
        ];

        proton-cachyos = mkOverlay [
          "proton-cachyos"
          "proton-cachyos-x86_64-v3"
          # Deprecated alias w/ underscores
          "proton-cachyos-x86_64_v3"
        ];

        vintagestory = mkOverlay [ "vintagestory" ];

        pokemmo = mkOverlay [ "pokemmo" ];

        pseudoregalia-rando = mkOverlay [ "pseudoregalia-rando" ];

        hytale-launcher = mkOverlay [
          "hytale-launcher"
          "hytale"
        ];

        # Disabled: millennium-steam is broken upstream. Re-enable if/when fixed.
        # millennium-steam = mkOverlay [ "millennium-steam" ];

        discord = mkOverlay [
          "discord"
          "vencord"
        ];

        fluxer = mkOverlay [ "fluxer-desktop" ];

        modengine3 = mkOverlay [ "modengine3" ];

        opengoal = mkOverlay [ "opengoal-launcher" ];

        jellium-desktop = mkOverlay [ "jellium-desktop" ];
      };

      nixosModules = {
        mesa-git = import ./modules/mesa-git.nix;
        default = self.nixosModules.mesa-git;
      };
    };
}
