# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  _2ship2harkinian = {
    pname = "_2ship2harkinian";
    version = "4.0.2";
    src = fetchgit {
      url = "https://github.com/HarbourMasters/2ship2harkinian.git";
      rev = "4.0.2";
      fetchSubmodules = true;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-3SgRvQL27e+MoTBGX4/iUwgELd6UFbjrb23gV1UvAJ8=";
    };
  };
  eden-emulator = {
    pname = "eden-emulator";
    version = "5ba3ae32dc040ac813c93512b0d90a22c4ec278a";
    src = fetchgit {
      url = "https://git.eden-emu.dev/eden-emu/eden.git";
      rev = "5ba3ae32dc040ac813c93512b0d90a22c4ec278a";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-v0FictPg+eO+fhL3ji48z+6bCn0sEmnBE3Y3I6X6gSI=";
    };
    date = "2026-06-06";
  };
  fluxer-desktop = {
    pname = "fluxer-desktop";
    version = "ee1f27fe1a372b5291aead8042944afd706bf5db";
    src = fetchgit {
      url = "https://github.com/fluxerapp/fluxer";
      rev = "ee1f27fe1a372b5291aead8042944afd706bf5db";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-94rLtgG5s/aJfNL2v/KTqLOnGsT05Qy6l3jPuL15SkE=";
    };
    date = "2026-04-09";
  };
  hytale-launcher = {
    pname = "hytale-launcher";
    version = "2026.05.29-125f35f";
    src = fetchurl {
      url = "https://launcher.hytale.com/builds/release/linux/amd64/hytale-launcher-2026.05.29-125f35f.zip";
      sha256 = "sha256-5hk1gzs6YCxM3GyYk/nZq8VRep+OnK19m/onN6rHkgQ=";
    };
  };
  jellyfin-desktop = {
    pname = "jellyfin-desktop";
    version = "3d4044082e8928b3445e635267e0444c4e5d8917";
    src = fetchgit {
      url = "https://github.com/jellyfin/jellyfin-desktop.git";
      rev = "3d4044082e8928b3445e635267e0444c4e5d8917";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-AjLqQWf0/KyCTeiL0HMvWRLYWT0vQhH0oa85kUYgaio=";
    };
    date = "2026-06-05";
  };
  libdrm = {
    pname = "libdrm";
    version = "e984d448b8b17aab853369e6c203e53719f46de1";
    src = fetchgit {
      url = "https://gitlab.freedesktop.org/mesa/drm.git";
      rev = "e984d448b8b17aab853369e6c203e53719f46de1";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-btHG+p8FJObTl/k04bDaRb7hclVtyijjLHqrFJ9aIM8=";
    };
    date = "2026-05-29";
  };
  mesa = {
    pname = "mesa";
    version = "31db17f653cbba464e432b3c4e2a144e2785425d";
    src = fetchgit {
      url = "https://gitlab.freedesktop.org/mesa/mesa.git";
      rev = "31db17f653cbba464e432b3c4e2a144e2785425d";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-5URtmdollIjhJpPjsJI+3Yv5JycRs233S5XorVPpgKY=";
    };
    date = "2026-06-05";
  };
  modengine3 = {
    pname = "modengine3";
    version = "v0.11.0";
    src = fetchurl {
      url = "https://github.com/garyttierney/me3/releases/download/v0.11.0/me3-linux-amd64.tar.gz";
      sha256 = "sha256-D+sJD3EN0AhUwWPmmJp7a9kVMEEQfHxoQb96OtTtjZc=";
    };
  };
  oodle-lib = {
    pname = "oodle-lib";
    version = "0.2.3";
    src = fetchurl {
      url = "https://github.com/new-world-tools/go-oodle/releases/download/v0.2.3-files/liboo2corelinux64.so.9";
      sha256 = "sha256-c1RlXrJbWH3DTL+YaWuR4w5tej8O7604cubBt274am4=";
    };
  };
  opengoal-launcher = {
    pname = "opengoal-launcher";
    version = "2.10.4";
    src = fetchurl {
      url = "https://github.com/open-goal/launcher/releases/download/v2.10.4/OpenGOAL-Launcher_2.10.4_amd64.AppImage";
      sha256 = "sha256-eikzjdOYNdJM9FM3O/HuCFDzf97Fm1nhbRedDyKZ1/s=";
    };
  };
  pokemmo = {
    pname = "pokemmo";
    version = "100884776";
    src = fetchurl {
      url = "https://pokemmo.com/download_file/1/";
      sha256 = "sha256-8foFB6p3K0Ija9ZQ+oam1tcGFka4wSJSOOOvtr6ydbU=";
    };
  };
  proton-cachyos = {
    pname = "proton-cachyos";
    version = "cachyos-11.0-20260521-slr";
    src = fetchurl {
      url = "https://github.com/CachyOS/proton-cachyos/releases/download/cachyos-11.0-20260521-slr/proton-cachyos-11.0-20260521-slr-x86_64.tar.xz";
      sha256 = "sha256-svDsjpMbAsvLV1xvTPHzeTKmSKOt0nHdfdEvE5X1tyw=";
    };
  };
  proton-cachyos-x86_64-v3 = {
    pname = "proton-cachyos-x86_64-v3";
    version = "cachyos-11.0-20260521-slr";
    src = fetchurl {
      url = "https://github.com/CachyOS/proton-cachyos/releases/download/cachyos-11.0-20260521-slr/proton-cachyos-11.0-20260521-slr-x86_64_v3.tar.xz";
      sha256 = "sha256-hWkZ+22va9Icx8DEj80k3lZId/jv/ETxXmB8UdwIz6U=";
    };
  };
  pseudoregalia-rando = {
    pname = "pseudoregalia-rando";
    version = "1.8.6";
    src = fetchurl {
      url = "https://github.com/pseudoregalia-modding/rando/archive/1.8.6.tar.gz";
      sha256 = "sha256-viI3nxgwdTxH3m4dG564Lay45Q2m1AUlelYsABAdt/Q=";
    };
  };
  shipwright = {
    pname = "shipwright";
    version = "9.2.3";
    src = fetchgit {
      url = "https://github.com/harbourmasters/shipwright.git";
      rev = "9.2.3";
      fetchSubmodules = true;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-tu6hS9Q/np4QqVHlI50QmhSOeVTO3RKolO2F2iSiU7Q=";
    };
  };
  vencord = {
    pname = "vencord";
    version = "9f2e6e7baf0aa68d2e612e6669319056b3def66e";
    src = fetchgit {
      url = "https://github.com/Vendicated/Vencord.git";
      rev = "9f2e6e7baf0aa68d2e612e6669319056b3def66e";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-U1xgdTSoVCiYxL3q8SmsQFs+RznnIBjbmSC1zqiSgmY=";
    };
    date = "2026-05-29";
  };
  vintagestory = {
    pname = "vintagestory";
    version = "stable/vs_client_linux-x64_1.22.3";
    src = fetchurl {
      url = "https://cdn.vintagestory.at/gamefiles/stable/vs_client_linux-x64_1.22.3.tar.gz";
      sha256 = "sha256-sa4Pj1DwT6W6LJCAYznmbyqPtMUTaLSNTkXS1imQp04=";
    };
  };
  wayland = {
    pname = "wayland";
    version = "1.25.0";
    src = fetchgit {
      url = "https://gitlab.freedesktop.org/wayland/wayland.git";
      rev = "1.25.0";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-aQTciXUsYIV5rWr2wNN+daH0KZfcrVSVZHoUdTutizM=";
    };
  };
  wayland-protocols = {
    pname = "wayland-protocols";
    version = "3de6742006076df4be038cbd325d011c93a1db90";
    src = fetchgit {
      url = "https://gitlab.freedesktop.org/wayland/wayland-protocols.git";
      rev = "3de6742006076df4be038cbd325d011c93a1db90";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-B6DKqyVFGIkKkK23uQr12whN2d73El94CUMZbMroDDM=";
    };
    date = "2026-05-30";
  };
}
