# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  discord = {
    pname = "discord";
    version = "0.0.123";
    src = fetchurl {
      url = "https://dl.discordapp.net/apps/linux/0.0.123/discord-0.0.123.tar.gz";
      sha256 = "sha256-2cNAfYzPbZ9O8s4b3RBLki8aM9TiFuZcGffFbY4zxJQ=";
    };
  };
  eden-emulator = {
    pname = "eden-emulator";
    version = "866881d0e36721f52ce3d788c2a33c28ad1fcaeb";
    src = fetchgit {
      url = "https://git.eden-emu.dev/eden-emu/eden.git";
      rev = "866881d0e36721f52ce3d788c2a33c28ad1fcaeb";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-7upoNV4j4vQW5YHsLQnRGl/L9abfILujZnn2/GbcarM=";
    };
    date = "2026-02-09";
  };
  hytale-launcher = {
    pname = "hytale-launcher";
    version = "2026.02.06-b95ae53";
    src = fetchurl {
      url = "https://launcher.hytale.com/builds/release/linux/amd64/hytale-launcher-2026.02.06-b95ae53.zip";
      sha256 = "sha256-p4tvm4j4o4BldlqJtaTrDJSPd6i/034rgG10FyQqrvE=";
    };
  };
  libdrm = {
    pname = "libdrm";
    version = "369990d9660a387f618d0eedc341eb285016243b";
    src = fetchgit {
      url = "https://gitlab.freedesktop.org/mesa/drm.git";
      rev = "369990d9660a387f618d0eedc341eb285016243b";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-kOaTjBeo4IsfWEk/JBTNId5ikrnpoc9DEjIl7DUd2yE=";
    };
    date = "2025-12-19";
  };
  mesa = {
    pname = "mesa";
    version = "fc814fa828e410b842408684066c8f8a48aefb2c";
    src = fetchgit {
      url = "https://gitlab.freedesktop.org/mesa/mesa.git";
      rev = "fc814fa828e410b842408684066c8f8a48aefb2c";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-59pKLb2YxhX/xwxyUEVt8hxCI2sT+yxCuk/vE7G2TWw=";
    };
    date = "2026-02-09";
  };
  oodle-lib = {
    pname = "oodle-lib";
    version = "0.2.3";
    src = fetchurl {
      url = "https://github.com/new-world-tools/go-oodle/releases/download/v0.2.3-files/liboo2corelinux64.so.9";
      sha256 = "sha256-c1RlXrJbWH3DTL+YaWuR4w5tej8O7604cubBt274am4=";
    };
  };
  pokemmo = {
    pname = "pokemmo";
    version = "694ca092-5f78c01";
    src = fetchurl {
      url = "https://pokemmo.com/download_file/1/";
      sha256 = "sha256-udw91RtbdJ3zv8xA9AwtibdghF4k0w7Db70UHMifASc=";
    };
  };
  proton-cachyos = {
    pname = "proton-cachyos";
    version = "cachyos-10.0-20260207-slr";
    src = fetchurl {
      url = "https://github.com/CachyOS/proton-cachyos/releases/download/cachyos-10.0-20260207-slr/proton-cachyos-10.0-20260207-slr-x86_64.tar.xz";
      sha256 = "sha256-hJKrcrrMbVx1gakpVWYWg9ALjq+uAfYeB/67JfFliTg=";
    };
  };
  proton-cachyos-x86_64-v2 = {
    pname = "proton-cachyos-x86_64-v2";
    version = "cachyos-10.0-20260207-slr";
    src = fetchurl {
      url = "https://github.com/CachyOS/proton-cachyos/releases/download/cachyos-10.0-20260207-slr/proton-cachyos-10.0-20260207-slr-x86_64_v2.tar.xz";
      sha256 = "sha256-mNUB/NXwTWDuP1PBVkENgMX8u53yzkP0dhQ8HnbUScs=";
    };
  };
  proton-cachyos-x86_64-v3 = {
    pname = "proton-cachyos-x86_64-v3";
    version = "cachyos-10.0-20260207-slr";
    src = fetchurl {
      url = "https://github.com/CachyOS/proton-cachyos/releases/download/cachyos-10.0-20260207-slr/proton-cachyos-10.0-20260207-slr-x86_64_v3.tar.xz";
      sha256 = "sha256-76iQrZKa2ysCDKV4jysWqthaiKMfjGWQR7r6IwilktI=";
    };
  };
  proton-cachyos-x86_64-v4 = {
    pname = "proton-cachyos-x86_64-v4";
    version = "cachyos-10.0-20260207-slr";
    src = fetchurl {
      url = "https://github.com/CachyOS/proton-cachyos/releases/download/cachyos-10.0-20260207-slr/proton-cachyos-10.0-20260207-slr-x86_64_v4.tar.xz";
      sha256 = "sha256-/GkMdSjP3DkbYjvvDEZvI2Na4WFW27zVwxkf9sLQj80=";
    };
  };
  pseudoregalia-rando = {
    pname = "pseudoregalia-rando";
    version = "1.8.6";
    src = fetchurl {
      url = "https://github.com/pseudoregalia-modding/rando/archive/1.8.6.tar.gz";
      sha256 = "sha256-viI3nxgwdTxH3m4dG564Lay45Q2m1AUlelYsABAdt/Q=";
    };
  };
  vencord = {
    pname = "vencord";
    version = "50c5124e1cc95062a883c58fc2551b302bd5994f";
    src = fetchgit {
      url = "https://github.com/Vendicated/Vencord.git";
      rev = "50c5124e1cc95062a883c58fc2551b302bd5994f";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-1459x8G0++jH6NO5n4B5LVjDFjAFkLKFAQygVdqgOAk=";
    };
    date = "2026-02-06";
  };
  vintagestory = {
    pname = "vintagestory";
    version = "stable/vs_client_linux-x64_1.21.6";
    src = fetchurl {
      url = "https://cdn.vintagestory.at/gamefiles/stable/vs_client_linux-x64_1.21.6.tar.gz";
      sha256 = "sha256-LkiL/8W9MKpmJxtK+s5JvqhOza0BLap1SsaDvbLYR0c=";
    };
  };
  vintagestory-stable = {
    pname = "vintagestory-stable";
    version = "1.21.6";
    src = fetchurl {
      url = "https://cdn.vintagestory.at/gamefiles/stable/vs_client_linux-x64_1.21.6.tar.gz";
      sha256 = "sha256-LkiL/8W9MKpmJxtK+s5JvqhOza0BLap1SsaDvbLYR0c=";
    };
  };
  wayland-protocols = {
    pname = "wayland-protocols";
    version = "ee95f9899e22df14035557e8977c2b99a7678f3b";
    src = fetchgit {
      url = "https://gitlab.freedesktop.org/wayland/wayland-protocols.git";
      rev = "ee95f9899e22df14035557e8977c2b99a7678f3b";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-2ixLGspkn8BVrUhP582kTZXdj0e+mNb2FsL6hvZsizM=";
    };
    date = "2026-02-05";
  };
}
