# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  _2ship2harkinian = {
    pname = "_2ship2harkinian";
    version = "4.0.2";
    src = fetchgit {
      url = "https://github.com/HarbourMasters/2ship2harkinian.git";
      rev = "4.0.2";
      fetchSubmodules = true;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-3SgRvQL27e+MoTBGX4/iUwgELd6UFbjrb23gV1UvAJ8=";
    };
  };
  eden-emulator = {
    pname = "eden-emulator";
    version = "ff7bbaea7db5a9a9528c1ef087d3a49a18931b52";
    src = fetchgit {
      url = "https://git.eden-emu.dev/eden-emu/eden.git";
      rev = "ff7bbaea7db5a9a9528c1ef087d3a49a18931b52";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-Fn/HqgyowIP0VDaF1vx/VJluj1mFFJSj5lGEHqZt+Y4=";
    };
    date = "2026-05-30";
  };
  fluxer-desktop = {
    pname = "fluxer-desktop";
    version = "ee1f27fe1a372b5291aead8042944afd706bf5db";
    src = fetchgit {
      url = "https://github.com/fluxerapp/fluxer";
      rev = "ee1f27fe1a372b5291aead8042944afd706bf5db";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-94rLtgG5s/aJfNL2v/KTqLOnGsT05Qy6l3jPuL15SkE=";
    };
    date = "2026-04-09";
  };
  hytale-launcher = {
    pname = "hytale-launcher";
    version = "2026.05.26-a9aec87";
    src = fetchurl {
      url = "https://launcher.hytale.com/builds/release/linux/amd64/hytale-launcher-2026.05.26-a9aec87.zip";
      sha256 = "sha256-N1x4iJtV7eidKKxx5g4ha8EaiAUnOivcFJhMSvVMR7w=";
    };
  };
  jellyfin-desktop = {
    pname = "jellyfin-desktop";
    version = "49af4a109dffacd15b5fa734dede58c9a493f490";
    src = fetchgit {
      url = "https://github.com/jellyfin/jellyfin-desktop.git";
      rev = "49af4a109dffacd15b5fa734dede58c9a493f490";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-zLL6XMKoZbstG43+Nv1u3LOTFg4keudoRn8V7RqwPeY=";
    };
    date = "2026-05-29";
  };
  libdrm = {
    pname = "libdrm";
    version = "e984d448b8b17aab853369e6c203e53719f46de1";
    src = fetchgit {
      url = "https://gitlab.freedesktop.org/mesa/drm.git";
      rev = "e984d448b8b17aab853369e6c203e53719f46de1";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-btHG+p8FJObTl/k04bDaRb7hclVtyijjLHqrFJ9aIM8=";
    };
    date = "2026-05-29";
  };
  mesa = {
    pname = "mesa";
    version = "154d3b581246613beff1dea1bc6b47824bf3a7ad";
    src = fetchgit {
      url = "https://gitlab.freedesktop.org/mesa/mesa.git";
      rev = "154d3b581246613beff1dea1bc6b47824bf3a7ad";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-C8l8DUVtZqW+2Lb1OAlq4Bk2sXwe/YwNjk1NHs25s6Y=";
    };
    date = "2026-05-30";
  };
  modengine3 = {
    pname = "modengine3";
    version = "v0.11.0";
    src = fetchurl {
      url = "https://github.com/garyttierney/me3/releases/download/v0.11.0/me3-linux-amd64.tar.gz";
      sha256 = "sha256-D+sJD3EN0AhUwWPmmJp7a9kVMEEQfHxoQb96OtTtjZc=";
    };
  };
  oodle-lib = {
    pname = "oodle-lib";
    version = "0.2.3";
    src = fetchurl {
      url = "https://github.com/new-world-tools/go-oodle/releases/download/v0.2.3-files/liboo2corelinux64.so.9";
      sha256 = "sha256-c1RlXrJbWH3DTL+YaWuR4w5tej8O7604cubBt274am4=";
    };
  };
  opengoal-launcher = {
    pname = "opengoal-launcher";
    version = "2.10.4";
    src = fetchurl {
      url = "https://github.com/open-goal/launcher/releases/download/v2.10.4/OpenGOAL-Launcher_2.10.4_amd64.AppImage";
      sha256 = "sha256-eikzjdOYNdJM9FM3O/HuCFDzf97Fm1nhbRedDyKZ1/s=";
    };
  };
  pokemmo = {
    pname = "pokemmo";
    version = "100884776";
    src = fetchurl {
      url = "https://pokemmo.com/download_file/1/";
      sha256 = "sha256-8foFB6p3K0Ija9ZQ+oam1tcGFka4wSJSOOOvtr6ydbU=";
    };
  };
  proton-cachyos = {
    pname = "proton-cachyos";
    version = "cachyos-11.0-20260520-slr";
    src = fetchurl {
      url = "https://github.com/CachyOS/proton-cachyos/releases/download/cachyos-11.0-20260520-slr/proton-cachyos-11.0-20260520-slr-x86_64.tar.xz";
      sha256 = "sha256-2einKIRxRfLegNaH7+kBlrpfkoOCQ6FzBdfczJ0uf5c=";
    };
  };
  proton-cachyos-x86_64-v3 = {
    pname = "proton-cachyos-x86_64-v3";
    version = "cachyos-11.0-20260520-slr";
    src = fetchurl {
      url = "https://github.com/CachyOS/proton-cachyos/releases/download/cachyos-11.0-20260520-slr/proton-cachyos-11.0-20260520-slr-x86_64_v3.tar.xz";
      sha256 = "sha256-YSDaUcoYYfT/UMkxpULfq7fVvELAhi8b/wIrpSv4yJQ=";
    };
  };
  pseudoregalia-rando = {
    pname = "pseudoregalia-rando";
    version = "1.8.6";
    src = fetchurl {
      url = "https://github.com/pseudoregalia-modding/rando/archive/1.8.6.tar.gz";
      sha256 = "sha256-viI3nxgwdTxH3m4dG564Lay45Q2m1AUlelYsABAdt/Q=";
    };
  };
  shipwright = {
    pname = "shipwright";
    version = "9.2.3";
    src = fetchgit {
      url = "https://github.com/harbourmasters/shipwright.git";
      rev = "9.2.3";
      fetchSubmodules = true;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-tu6hS9Q/np4QqVHlI50QmhSOeVTO3RKolO2F2iSiU7Q=";
    };
  };
  vencord = {
    pname = "vencord";
    version = "9f2e6e7baf0aa68d2e612e6669319056b3def66e";
    src = fetchgit {
      url = "https://github.com/Vendicated/Vencord.git";
      rev = "9f2e6e7baf0aa68d2e612e6669319056b3def66e";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-U1xgdTSoVCiYxL3q8SmsQFs+RznnIBjbmSC1zqiSgmY=";
    };
    date = "2026-05-29";
  };
  vintagestory = {
    pname = "vintagestory";
    version = "stable/vs_client_linux-x64_1.22.2";
    src = fetchurl {
      url = "https://cdn.vintagestory.at/gamefiles/stable/vs_client_linux-x64_1.22.2.tar.gz";
      sha256 = "sha256-caLSOm/WXpXrjC1az72Nc0XDWOpWB2R9iVq8ShDEZgU=";
    };
  };
  wayland = {
    pname = "wayland";
    version = "1.25.0";
    src = fetchgit {
      url = "https://gitlab.freedesktop.org/wayland/wayland.git";
      rev = "1.25.0";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-aQTciXUsYIV5rWr2wNN+daH0KZfcrVSVZHoUdTutizM=";
    };
  };
  wayland-protocols = {
    pname = "wayland-protocols";
    version = "1571cf6ae9f8ed2d5b3b8f65bee758cad025375b";
    src = fetchgit {
      url = "https://gitlab.freedesktop.org/wayland/wayland-protocols.git";
      rev = "1571cf6ae9f8ed2d5b3b8f65bee758cad025375b";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-NY5fX4bpw6PnQBmma+Xa5F04/b5fsqR9Ws/H3Rvsmr8=";
    };
    date = "2026-05-29";
  };
}
