# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  biscuit = {
    pname = "biscuit";
    version = "7dc44a52c81855a75e9ecafa4e7f2af3593586f3";
    src = fetchFromGitHub {
      owner = "lioncash";
      repo = "biscuit";
      rev = "7dc44a52c81855a75e9ecafa4e7f2af3593586f3";
      fetchSubmodules = false;
      sha256 = "sha256-qkm8+Kxg2jEAgMdyJGC+86e+vIcY4uFpTa+HHU2F/pI=";
    };
    date = "2026-01-29";
  };
  cpp-jwt = {
    pname = "cpp-jwt";
    version = "9eaea6328fae768d1cc524a27f0db6250e0a165a";
    src = fetchFromGitHub {
      owner = "crueter";
      repo = "cpp-jwt";
      rev = "9eaea6328fae768d1cc524a27f0db6250e0a165a";
      fetchSubmodules = false;
      sha256 = "sha256-r4Kf7k0tfDzrFSCS6f8bmEAmzctXsMBSd+t9xlqfvNs=";
    };
    date = "2025-09-08";
  };
  discord-rpc = {
    pname = "discord-rpc";
    version = "0d8b2d6a37c6e47d62b37caa14708bf747c883bb";
    src = fetchFromGitHub {
      owner = "eden-emulator";
      repo = "discord-rpc";
      rev = "0d8b2d6a37c6e47d62b37caa14708bf747c883bb";
      fetchSubmodules = false;
      sha256 = "sha256-bsVW2yKgTyIPDyVLKYHxlllLhcY9H5B81+23zJLBIBY=";
    };
    date = "2025-10-23";
  };
  frozen = {
    pname = "frozen";
    version = "61dce5ae18ca59931e27675c468e64118aba8744";
    src = fetchFromGitHub {
      owner = "serge-sans-paille";
      repo = "frozen";
      rev = "61dce5ae18ca59931e27675c468e64118aba8744";
      fetchSubmodules = false;
      sha256 = "sha256-zIczBSRDWjX9hcmYWYkbWY3NAAQwQtKhMTeHlYp4BKk=";
    };
    date = "2025-07-29";
  };
  libadrenotools = {
    pname = "libadrenotools";
    version = "8fae8ce254dfc1344527e05301e43f37dea2df80";
    src = fetchFromGitHub {
      owner = "bylaws";
      repo = "libadrenotools";
      rev = "8fae8ce254dfc1344527e05301e43f37dea2df80";
      fetchSubmodules = false;
      sha256 = "sha256-bgwqavEVpvRLLl0uETEFpiDraNmHdZywspeMV01N6lI=";
    };
    date = "2024-09-10";
  };
  mcl = {
    pname = "mcl";
    version = "5fc4beaf331037649b10625736b41365defb4f50";
    src = fetchFromGitHub {
      owner = "azahar-emu";
      repo = "mcl";
      rev = "5fc4beaf331037649b10625736b41365defb4f50";
      fetchSubmodules = false;
      sha256 = "sha256-7lHOjlUvCQsct/pijn0M0OOG5LpExmXwB6kH+ostA2I=";
    };
    date = "2026-01-04";
  };
  nx_tzdb = {
    pname = "nx_tzdb";
    version = "221202";
    src = fetchurl {
      url = "https://github.com/lat9nq/tzdb_to_nx/releases/download/221202/221202.zip";
      sha256 = "sha256-mRzW+iIwrU1zsxHmf+0RArU8BShAoEMvCz+McXFFK3c=";
    };
  };
  oaknut = {
    pname = "oaknut";
    version = "a89bcf601f724e4b49e4ffea96aa51db5e0fbb69";
    src = fetchFromGitHub {
      owner = "eden-emulator";
      repo = "oaknut";
      rev = "a89bcf601f724e4b49e4ffea96aa51db5e0fbb69";
      fetchSubmodules = false;
      sha256 = "sha256-NWJMottKMiG6Rk2/ACNtBiYfWDsCeSGznPTqVO809P0=";
    };
    date = "2025-10-04";
  };
  quazip = {
    pname = "quazip";
    version = "f838774d6306eb5a500af9ab336ec85f01ebd7ec";
    src = fetchFromGitHub {
      owner = "crueter";
      repo = "quazip-qt6";
      rev = "f838774d6306eb5a500af9ab336ec85f01ebd7ec";
      fetchSubmodules = false;
      sha256 = "sha256-Jp+v7uwoPxvarzOclgSnoGcwAPXKnm23yrZKtjJCHro=";
    };
    date = "2025-07-17";
  };
  simpleini = {
    pname = "simpleini";
    version = "18fd1db7fcfee664c174719f062b2598772c8be6";
    src = fetchFromGitHub {
      owner = "brofield";
      repo = "simpleini";
      rev = "18fd1db7fcfee664c174719f062b2598772c8be6";
      fetchSubmodules = false;
      sha256 = "sha256-1JTVjMfEuWqlyYAm4Er6HPjrP2Tnt0ntai8oVvIEOu0=";
    };
    date = "2025-11-14";
  };
  sirit = {
    pname = "sirit";
    version = "e3cf3924bf15875ea4ec8bf6af9d693dc2266db1";
    src = fetchFromGitHub {
      owner = "eden-emulator";
      repo = "sirit";
      rev = "e3cf3924bf15875ea4ec8bf6af9d693dc2266db1";
      fetchSubmodules = false;
      sha256 = "sha256-ThyUaoVmnYz9eQ1a19BbLhqfOpPxRjSovBl2wvlfRoI=";
    };
    date = "2026-01-09";
  };
  unordered-dense = {
    pname = "unordered-dense";
    version = "7b55cab8418da1603496462ce3ccdb4cb1dc3368";
    src = fetchFromGitHub {
      owner = "martinus";
      repo = "unordered_dense";
      rev = "7b55cab8418da1603496462ce3ccdb4cb1dc3368";
      fetchSubmodules = false;
      sha256 = "sha256-yCdn3/OIGLH5uW6BgvfbxPYwtiWivOHabfxaYrQromE=";
    };
    date = "2026-02-04";
  };
  xbyak = {
    pname = "xbyak";
    version = "3fe4856d12a44603dee3eced00f242e279666757";
    src = fetchFromGitHub {
      owner = "herumi";
      repo = "xbyak";
      rev = "3fe4856d12a44603dee3eced00f242e279666757";
      fetchSubmodules = false;
      sha256 = "sha256-dZgEjyVwr2Bg49k6f5yETLHsk+LevNdvq0BOCZsZ3nA=";
    };
    date = "2026-02-13";
  };
}
