# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  biscuit = {
    pname = "biscuit";
    version = "v0.19.0";
    src = fetchFromGitHub {
      owner = "lioncash";
      repo = "biscuit";
      rev = "v0.19.0";
      fetchSubmodules = false;
      sha256 = "sha256-fexoArbU317sB4scZTRijfzpe/kiltTFesn5e0C4pyw=";
    };
  };
  cpp-jwt = {
    pname = "cpp-jwt";
    version = "9eaea6328fae768d1cc524a27f0db6250e0a165a";
    src = fetchFromGitHub {
      owner = "crueter";
      repo = "cpp-jwt";
      rev = "9eaea6328fae768d1cc524a27f0db6250e0a165a";
      fetchSubmodules = false;
      sha256 = "sha256-r4Kf7k0tfDzrFSCS6f8bmEAmzctXsMBSd+t9xlqfvNs=";
    };
    date = "2025-09-08";
  };
  discord-rpc = {
    pname = "discord-rpc";
    version = "0d8b2d6a37c6e47d62b37caa14708bf747c883bb";
    src = fetchFromGitHub {
      owner = "eden-emulator";
      repo = "discord-rpc";
      rev = "0d8b2d6a37c6e47d62b37caa14708bf747c883bb";
      fetchSubmodules = false;
      sha256 = "sha256-bsVW2yKgTyIPDyVLKYHxlllLhcY9H5B81+23zJLBIBY=";
    };
    date = "2025-10-23";
  };
  frozen = {
    pname = "frozen";
    version = "61dce5ae18ca59931e27675c468e64118aba8744";
    src = fetchFromGitHub {
      owner = "serge-sans-paille";
      repo = "frozen";
      rev = "61dce5ae18ca59931e27675c468e64118aba8744";
      fetchSubmodules = false;
      sha256 = "sha256-zIczBSRDWjX9hcmYWYkbWY3NAAQwQtKhMTeHlYp4BKk=";
    };
    date = "2025-07-29";
  };
  libadrenotools = {
    pname = "libadrenotools";
    version = "8fae8ce254dfc1344527e05301e43f37dea2df80";
    src = fetchFromGitHub {
      owner = "bylaws";
      repo = "libadrenotools";
      rev = "8fae8ce254dfc1344527e05301e43f37dea2df80";
      fetchSubmodules = false;
      sha256 = "sha256-bgwqavEVpvRLLl0uETEFpiDraNmHdZywspeMV01N6lI=";
    };
    date = "2024-09-10";
  };
  mcl = {
    pname = "mcl";
    version = "5fc4beaf331037649b10625736b41365defb4f50";
    src = fetchFromGitHub {
      owner = "azahar-emu";
      repo = "mcl";
      rev = "5fc4beaf331037649b10625736b41365defb4f50";
      fetchSubmodules = false;
      sha256 = "sha256-7lHOjlUvCQsct/pijn0M0OOG5LpExmXwB6kH+ostA2I=";
    };
    date = "2026-01-04";
  };
  nx_tzdb = {
    pname = "nx_tzdb";
    version = "121125";
    src = fetchurl {
      url = "https://git.crueter.xyz/misc/tzdb_to_nx/releases/download/121125/121125.tar.gz";
      sha256 = "sha256-wX3BUywYcZFVrOQk8VhByd/GY2gb/sawC7ft2IRC/wI=";
    };
  };
  oaknut = {
    pname = "oaknut";
    version = "v2.0.3";
    src = fetchFromGitHub {
      owner = "eden-emulator";
      repo = "oaknut";
      rev = "v2.0.3";
      fetchSubmodules = false;
      sha256 = "sha256-NWJMottKMiG6Rk2/ACNtBiYfWDsCeSGznPTqVO809P0=";
    };
  };
  quazip = {
    pname = "quazip";
    version = "f838774d6306eb5a500af9ab336ec85f01ebd7ec";
    src = fetchFromGitHub {
      owner = "crueter";
      repo = "quazip-qt6";
      rev = "f838774d6306eb5a500af9ab336ec85f01ebd7ec";
      fetchSubmodules = false;
      sha256 = "sha256-Jp+v7uwoPxvarzOclgSnoGcwAPXKnm23yrZKtjJCHro=";
    };
    date = "2025-07-17";
  };
  simpleini = {
    pname = "simpleini";
    version = "v4.25";
    src = fetchFromGitHub {
      owner = "brofield";
      repo = "simpleini";
      rev = "v4.25";
      fetchSubmodules = false;
      sha256 = "sha256-1JTVjMfEuWqlyYAm4Er6HPjrP2Tnt0ntai8oVvIEOu0=";
    };
  };
  sirit = {
    pname = "sirit";
    version = "v1.0.3";
    src = fetchFromGitHub {
      owner = "eden-emulator";
      repo = "sirit";
      rev = "v1.0.3";
      fetchSubmodules = false;
      sha256 = "sha256-eBr+KorrAOFVzxRGZ2L3H6abfNAGrdVvO/NzOFwauTA=";
    };
  };
  unordered-dense = {
    pname = "unordered-dense";
    version = "7b55cab8418da1603496462ce3ccdb4cb1dc3368";
    src = fetchFromGitHub {
      owner = "martinus";
      repo = "unordered_dense";
      rev = "7b55cab8418da1603496462ce3ccdb4cb1dc3368";
      fetchSubmodules = false;
      sha256 = "sha256-yCdn3/OIGLH5uW6BgvfbxPYwtiWivOHabfxaYrQromE=";
    };
    date = "2026-02-04";
  };
  xbyak = {
    pname = "xbyak";
    version = "v7.33.2";
    src = fetchFromGitHub {
      owner = "herumi";
      repo = "xbyak";
      rev = "v7.33.2";
      fetchSubmodules = false;
      sha256 = "sha256-7HFvZ6wr7X7K5rrw9k/LWXEazJ67Hm8IqO2edcEU1pI=";
    };
  };
}
