# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  cpp-jwt = {
    pname = "cpp-jwt";
    version = "9eaea6328fae768d1cc524a27f0db6250e0a165a";
    src = fetchFromGitHub {
      owner = "crueter";
      repo = "cpp-jwt";
      rev = "9eaea6328fae768d1cc524a27f0db6250e0a165a";
      fetchSubmodules = false;
      sha256 = "sha256-r4Kf7k0tfDzrFSCS6f8bmEAmzctXsMBSd+t9xlqfvNs=";
    };
    date = "2025-09-08";
  };
  discord-rpc = {
    pname = "discord-rpc";
    version = "0d8b2d6a37c6e47d62b37caa14708bf747c883bb";
    src = fetchFromGitHub {
      owner = "eden-emulator";
      repo = "discord-rpc";
      rev = "0d8b2d6a37c6e47d62b37caa14708bf747c883bb";
      fetchSubmodules = false;
      sha256 = "sha256-bsVW2yKgTyIPDyVLKYHxlllLhcY9H5B81+23zJLBIBY=";
    };
    date = "2025-10-23";
  };
  frozen = {
    pname = "frozen";
    version = "b07a5c8187bc3e6f1461efab89fe07f467e300db";
    src = fetchFromGitHub {
      owner = "serge-sans-paille";
      repo = "frozen";
      rev = "b07a5c8187bc3e6f1461efab89fe07f467e300db";
      fetchSubmodules = false;
      sha256 = "sha256-eZdiLKUcx1MTcW+HyoRi6U/lUbs/qAQhRw0wX3tpUjY=";
    };
    date = "2026-04-20";
  };
  httplib = {
    pname = "httplib";
    version = "v0.37.0";
    src = fetchFromGitHub {
      owner = "yhirose";
      repo = "cpp-httplib";
      rev = "v0.37.0";
      fetchSubmodules = false;
      sha256 = "sha256-I7mfT4Eb5sXUURReq3nzQRUhI4sMx4wQpdJBw+vOA/s=";
    };
  };
  nx_tzdb = {
    pname = "nx_tzdb";
    version = "121125";
    src = fetchurl {
      url = "https://git.crueter.xyz/misc/tzdb_to_nx/releases/download/121125/121125.tar.gz";
      sha256 = "sha256-wX3BUywYcZFVrOQk8VhByd/GY2gb/sawC7ft2IRC/wI=";
    };
  };
  quazip = {
    pname = "quazip";
    version = "f838774d6306eb5a500af9ab336ec85f01ebd7ec";
    src = fetchFromGitHub {
      owner = "crueter";
      repo = "quazip-qt6";
      rev = "f838774d6306eb5a500af9ab336ec85f01ebd7ec";
      fetchSubmodules = false;
      sha256 = "sha256-Jp+v7uwoPxvarzOclgSnoGcwAPXKnm23yrZKtjJCHro=";
    };
    date = "2025-07-17";
  };
  simpleini = {
    pname = "simpleini";
    version = "v4.25";
    src = fetchFromGitHub {
      owner = "brofield";
      repo = "simpleini";
      rev = "v4.25";
      fetchSubmodules = false;
      sha256 = "sha256-1JTVjMfEuWqlyYAm4Er6HPjrP2Tnt0ntai8oVvIEOu0=";
    };
  };
  sirit = {
    pname = "sirit";
    version = "v1.0.4";
    src = fetchFromGitHub {
      owner = "eden-emulator";
      repo = "sirit";
      rev = "v1.0.4";
      fetchSubmodules = false;
      sha256 = "sha256-ThyUaoVmnYz9eQ1a19BbLhqfOpPxRjSovBl2wvlfRoI=";
    };
  };
  unordered-dense = {
    pname = "unordered-dense";
    version = "7b55cab8418da1603496462ce3ccdb4cb1dc3368";
    src = fetchFromGitHub {
      owner = "martinus";
      repo = "unordered_dense";
      rev = "7b55cab8418da1603496462ce3ccdb4cb1dc3368";
      fetchSubmodules = false;
      sha256 = "sha256-yCdn3/OIGLH5uW6BgvfbxPYwtiWivOHabfxaYrQromE=";
    };
    date = "2026-02-04";
  };
  xbyak = {
    pname = "xbyak";
    version = "v7.35.2";
    src = fetchFromGitHub {
      owner = "herumi";
      repo = "xbyak";
      rev = "v7.35.2";
      fetchSubmodules = false;
      sha256 = "sha256-JE3Sc+l8amoVwOfj03KKiwsOfEiNPaFRrV4aXDcb3+g=";
    };
  };
}
