{
  pkgs,
  vencordSrc,
}:

let
  lib = pkgs.lib;

  # Read the PNPM hash generated by Github Actions
  pnpmHash = lib.fileContents ./vencord-pnpm-hash.txt;

  # Discord source manifest (version + distro + per-module brotli archives),
  # refreshed by scripts/sync-discord-deps.py from the distributions API.
  source = lib.importJSON ./sources.json;

  vencord-git = pkgs.vencord.overrideAttrs (
    finalAttrs: _prev: {
      pname = "vencord-git";
      version = vencordSrc.version;
      src = vencordSrc.src;

      # Forward patches/postPatch — upstream's fix-deps.patch and the
      # @types/react bump have to apply before the pnpm lockfile is resolved
      # or the deps hash will not match.
      pnpmDeps = pkgs.fetchPnpmDeps {
        inherit (finalAttrs)
          pname
          src
          patches
          postPatch
          ;
        pnpm = pkgs.pnpm_10;
        fetcherVersion = 3;
        hash = pnpmHash;
      };

      env = {
        VENCORD_REMOTE = "Vendicated/Vencord";
        VENCORD_HASH = vencordSrc.version;
      };

      passthru = { };
    }
  );

  discord-stable = pkgs.discord.override {
    inherit source;
    withVencord = true;
    vencord = vencord-git;
  };

in
{
  discord = discord-stable;
  vencord = vencord-git;
}
