#!/usr/bin/env bash
set -euo pipefail

# Syncs pkgs/eden-emulator/nvfetcher.toml with Eden's upstream cpmfile.json
# nvfetcher -o _sources && ./scripts/sync-eden-deps.sh
# nvfetcher -c pkgs/eden-emulator/nvfetcher.toml -o pkgs/eden-emulator/_dependencies

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SOURCES_JSON="$REPO_ROOT/_sources/generated.json"
EDEN_NVFETCHER="$REPO_ROOT/pkgs/eden-emulator/nvfetcher.toml"
EDEN_RAW="https://git.eden-emu.dev/eden-emu/eden/raw"

REV=$(jq -r '.["eden-emulator"].version // empty' "$SOURCES_JSON")
if [[ -z "$REV" ]]; then
    echo "Error: eden-emulator not in _sources/generated.json" >&2
    exit 1
fi
echo "Syncing Eden CPM deps @ ${REV:0:10}..." >&2

# Fetch and merge both cpmfile.json files into one object
TMPDIR=$(mktemp -d)
trap 'rm -rf "$TMPDIR"' EXIT
echo '{}' > "$TMPDIR/externals.json"
echo '{}' > "$TMPDIR/root.json"

for pair in "externals/cpmfile.json:externals.json" "cpmfile.json:root.json"; do
    remote="${pair%%:*}" local_file="${pair##*:}"
    if curl -fsSL "$EDEN_RAW/$REV/$remote" -o "$TMPDIR/$local_file" 2>/dev/null; then
        echo "  Fetched $remote" >&2
    fi
done
CPM=$(jq -s '.[0] * .[1]' "$TMPDIR/externals.json" "$TMPDIR/root.json")

if [[ "$(echo "$CPM" | jq 'length')" -eq 0 ]]; then
    echo "Error: no CPM deps found" >&2; exit 1
fi

# Patched forks — always use these instead of upstream repos
declare -A REPO_OVERRIDES=(
    ["cpp-jwt"]="crueter/cpp-jwt"
    ["quazip"]="crueter/quazip-qt6"
)

get_repo() {
    local name="$1" cpm_repo="$2"
    echo "${REPO_OVERRIDES[$name]:-$cpm_repo}"
}

# nvfetcher_name:cpmfile_key
NEEDED_DEPS=(
    biscuit:biscuit cpp-jwt:cpp-jwt discord-rpc:discord-rpc frozen:frozen
    libadrenotools:libadrenotools mcl:mcl oaknut:oaknut quazip:quazip
    simpleini:simpleini sirit:sirit unordered-dense:unordered-dense xbyak:xbyak
)

# Generate nvfetcher.toml
{
    cat <<'HEADER'
# pkgs/eden-emulator/nvfetcher.toml
# Auto-generated by scripts/sync-eden-deps.sh — do not edit manually.
HEADER
    echo ""

    for entry in "${NEEDED_DEPS[@]}"; do
        nvf="${entry%%:*}" key="${entry##*:}"
        echo "$CPM" | jq -e --arg k "$key" '.[$k]' >/dev/null 2>&1 || continue
        [[ "$(echo "$CPM" | jq -r --arg k "$key" '.[$k].ci // false')" == "true" ]] && continue

        cpm_repo=$(echo "$CPM" | jq -r --arg k "$key" '.[$k].repo // ""')
        tag=$(echo "$CPM" | jq -r --arg k "$key" '.[$k].tag // ""')
        git_ver=$(echo "$CPM" | jq -r --arg k "$key" '.[$k].git_version // ""')
        sha=$(echo "$CPM" | jq -r --arg k "$key" '.[$k].sha // ""')

        repo=$(get_repo "$nvf" "$cpm_repo")
        [[ -z "$repo" ]] && continue

        echo "[$nvf]"
        [[ "$repo" != "$cpm_repo" && -n "$cpm_repo" ]] && echo "# upstream: $cpm_repo"

        if [[ -n "$git_ver" && -n "$tag" ]]; then
            echo "src.manual = \"${tag/\%VERSION\%/$git_ver}\""
        else
            [[ -n "$sha" ]] && echo "# cpmfile.json sha: $sha"
            echo "src.git = \"https://github.com/$repo.git\""
        fi
        echo "fetch.github = \"$repo\""
        echo ""
    done

    # nx_tzdb (custom git host)
    if echo "$CPM" | jq -e '.tzdb' >/dev/null 2>&1; then
        ver=$(echo "$CPM" | jq -r '.tzdb.version')
        host=$(echo "$CPM" | jq -r '.tzdb.git_host // ""')
        repo=$(echo "$CPM" | jq -r '.tzdb.repo')
        artifact=$(echo "$CPM" | jq -r '.tzdb.artifact' | sed "s/%VERSION%/$ver/g")
        tag=$(echo "$CPM" | jq -r '.tzdb.tag' | sed "s/%VERSION%/$ver/g")

        echo "[nx_tzdb]"
        echo "src.manual = \"$ver\""
        if [[ -n "$host" ]]; then
            echo "fetch.url = \"https://$host/$repo/releases/download/$tag/$artifact\""
        else
            echo "fetch.url = \"https://github.com/$repo/releases/download/$tag/$artifact\""
        fi
        echo ""
    fi

} > "$EDEN_NVFETCHER.new"

if [[ -f "$EDEN_NVFETCHER" ]] && diff -q "$EDEN_NVFETCHER" "$EDEN_NVFETCHER.new" >/dev/null 2>&1; then
    rm "$EDEN_NVFETCHER.new"
    echo "Eden CPM deps already up to date." >&2
else
    mv "$EDEN_NVFETCHER.new" "$EDEN_NVFETCHER"
    echo "Updated pkgs/eden-emulator/nvfetcher.toml" >&2
fi
