#!/usr/bin/env bash
set -euo pipefail

# Syncs Eden's upstream cpmfile.json into:
#   - pkgs/eden-emulator/nvfetcher.toml      (one entry per vendored dep)
#   - pkgs/eden-emulator/default.nix         (cpmSources, between markers)
#
# Usage:
#   nvfetcher -o _sources && ./scripts/sync-eden-deps.sh
#   nvfetcher -c pkgs/eden-emulator/nvfetcher.toml -o pkgs/eden-emulator/_dependencies

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SOURCES_JSON="$REPO_ROOT/_sources/generated.json"
EDEN_NVFETCHER="$REPO_ROOT/pkgs/eden-emulator/nvfetcher.toml"
EDEN_DEFAULT_NIX="$REPO_ROOT/pkgs/eden-emulator/default.nix"
EDEN_GIT="https://git.eden-emu.dev/eden-emu/eden.git"

# Patched forks — always use these instead of upstream repos.
declare -A REPO_OVERRIDES=(
    ["cpp-jwt"]="crueter/cpp-jwt"
    ["quazip"]="crueter/quazip-qt6"
)

# Deps we don't vendor. Two reasons:
# provided by nixpkgs (we add them to buildInputs in default.nix)
# irrelevant to x86_64-linux, or CI/build-only metadata
SKIP_DEPS=(
    boost boost_headers fmt lz4 zstd nlohmann openssl opus zlib
    catch2 cubeb enet gamemode libusb
    spirv-headers spirv-tools
    vulkan-headers vulkan-utility-libraries vulkan-memory-allocator
    vulkan-validation-layers
    sdl3 sdl3-ci ffmpeg
    oaknut biscuit libadrenotools moltenvk oboe llvm-mingw
    ffmpeg-ci sirit-ci tzdb
)

REV=$(jq -r '.["eden-emulator"].version // empty' "$SOURCES_JSON")
if [[ -z "$REV" ]]; then
    echo "Error: eden-emulator not in _sources/generated.json" >&2
    exit 1
fi
echo "Syncing Eden CPM deps @ ${REV:0:10}..." >&2

# Fetch cpmfile.json via git (Cloudflare blocks raw HTTP access).
TMPDIR=$(mktemp -d)
trap 'rm -rf "$TMPDIR"' EXIT

git clone --depth=1 --no-checkout -q "$EDEN_GIT" "$TMPDIR/eden"
if ! git -C "$TMPDIR/eden" checkout HEAD -- cpmfile.json 2>/dev/null; then
    echo "Error: failed to check out cpmfile.json from $EDEN_GIT" >&2
    echo "       Eden likely restructured their CPM tooling and renamed or" >&2
    echo "       removed cpmfile.json. Inspect the repo layout and update the" >&2
    echo "       checkout path in this script accordingly." >&2
    exit 1
fi

echo "  Fetched cpmfile.json via git" >&2
CPM=$(jq '.' "$TMPDIR/eden/cpmfile.json")

if [[ "$(echo "$CPM" | jq 'length')" -eq 0 ]]; then
    echo "Error: no CPM deps found" >&2; exit 1
fi

# every vendored non-CI cpmfile entry with a repo that isn't in SKIP_DEPS.
declare -A SKIP_SET=()
for s in "${SKIP_DEPS[@]}"; do SKIP_SET[$s]=1; done

mapfile -t ALL_KEYS < <(
    echo "$CPM" | jq -r '
        to_entries
        | map(select(.value.ci != true and .value.repo != null))
        | sort_by(.key)
        | .[].key
    '
)
NEEDED_DEPS=()
for k in "${ALL_KEYS[@]}"; do
    [[ -n "${SKIP_SET[$k]:-}" ]] || NEEDED_DEPS+=("$k")
done

# Generate nvfetcher.toml
{
    cat <<'HEADER'
# pkgs/eden-emulator/nvfetcher.toml
# Auto-generated by scripts/sync-eden-deps.sh — do not edit manually.
HEADER
    echo ""

    for nvf in "${NEEDED_DEPS[@]}"; do
        cpm_repo=$(echo "$CPM" | jq -r --arg k "$nvf" '.[$k].repo // ""')
        tag=$(echo "$CPM" | jq -r --arg k "$nvf" '.[$k].tag // ""')
        # Eden renamed git_version -> version; accept either for compatibility.
        git_ver=$(echo "$CPM" | jq -r --arg k "$nvf" '.[$k].git_version // .[$k].version // ""')
        sha=$(echo "$CPM" | jq -r --arg k "$nvf" '.[$k].sha // ""')

        repo="${REPO_OVERRIDES[$nvf]:-$cpm_repo}"

        echo "[$nvf]"
        [[ "$repo" != "$cpm_repo" && -n "$cpm_repo" ]] && echo "# upstream: $cpm_repo"

        if [[ -n "$git_ver" && -n "$tag" ]]; then
            echo "src.manual = \"${tag/\%VERSION\%/$git_ver}\""
        else
            [[ -n "$sha" ]] && echo "# cpmfile.json sha: $sha"
            echo "src.git = \"https://github.com/$repo.git\""
        fi
        echo "fetch.github = \"$repo\""
        echo ""
    done

    # nx_tzdb (special-cased — uses a release artifact). We prefer the
    # git.crueter.xyz mirror because Cloudflare challenges can block release
    # downloads from git.eden-emu.dev in CI. The mirror lags upstream, though,
    # so when it doesn't yet carry the pinned version we fall back to the
    # upstream git_host from cpmfile.json.
    if echo "$CPM" | jq -e '.tzdb' >/dev/null 2>&1; then
        ver=$(echo "$CPM" | jq -r '.tzdb.version')
        git_host=$(echo "$CPM" | jq -r '.tzdb.git_host')
        repo=$(echo "$CPM" | jq -r '.tzdb.repo')
        artifact=$(echo "$CPM" | jq -r '.tzdb.artifact' | sed "s/%VERSION%/$ver/g")
        tag=$(echo "$CPM" | jq -r '.tzdb.tag' | sed "s/%VERSION%/$ver/g")

        mirror_url="https://git.crueter.xyz/misc/tzdb_to_nx/releases/download/$tag/$artifact"
        upstream_url="https://$git_host/$repo/releases/download/$tag/$artifact"

        if curl -sfIL --max-time 30 "$mirror_url" >/dev/null 2>&1; then
            tzdb_url="$mirror_url"
        else
            echo "  nx_tzdb $ver not on git.crueter.xyz mirror; falling back to $git_host" >&2
            tzdb_url="$upstream_url"
        fi

        echo "[nx_tzdb]"
        echo "src.manual = \"$ver\""
        echo "fetch.url = \"$tzdb_url\""
        echo ""
    fi

} > "$EDEN_NVFETCHER.new"

if [[ -f "$EDEN_NVFETCHER" ]] && diff -q "$EDEN_NVFETCHER" "$EDEN_NVFETCHER.new" >/dev/null 2>&1; then
    rm "$EDEN_NVFETCHER.new"
    echo "nvfetcher.toml already up to date." >&2
else
    mv "$EDEN_NVFETCHER.new" "$EDEN_NVFETCHER"
    echo "Updated pkgs/eden-emulator/nvfetcher.toml" >&2
fi

# Rebuild the cpmSources block in default.nix between marker comments
SOURCES_BLOCK=""
for nvf in "${NEEDED_DEPS[@]}"; do
    pkg=$(echo "$CPM" | jq -r --arg k "$nvf" '.[$k].package // $k')
    SOURCES_BLOCK+="    ${pkg} = cpm.${nvf}.src;"$'\n'
done

awk -v block="$SOURCES_BLOCK" '
    BEGIN { in_block = 0 }
    /# >>> AUTO-CPM-SOURCES/ {
        print
        printf "%s", block
        in_block = 1
        next
    }
    /# <<< AUTO-CPM-SOURCES/ {
        in_block = 0
        print
        next
    }
    !in_block { print }
' "$EDEN_DEFAULT_NIX" > "$EDEN_DEFAULT_NIX.new"

if diff -q "$EDEN_DEFAULT_NIX" "$EDEN_DEFAULT_NIX.new" >/dev/null 2>&1; then
    rm "$EDEN_DEFAULT_NIX.new"
    echo "default.nix cpmSources already up to date." >&2
else
    mv "$EDEN_DEFAULT_NIX.new" "$EDEN_DEFAULT_NIX"
    echo "Updated pkgs/eden-emulator/default.nix cpmSources" >&2
fi

echo "Vendored ${#NEEDED_DEPS[@]} CPM entries." >&2
